import '@/styles/globals.css'
import { ChakraProvider } from '@chakra-ui/react'
import Head from 'next/head'
import Banner from '@/components/Banner'

export default function App({ Component, pageProps }) {
  return(
    <>
     <Head>
        <title>The Headliner</title>
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <style>
  @import url('https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200;0,400;0,500;1,300&family=Work+Sans:wght@300&display=swap');
</style>
       
      </Head>
      <ChakraProvider>
        <Banner />
        <Component {...pageProps} />
      </ChakraProvider>
    </>
  )
}
